app-emulation/docker: disable optimizations
With optimizations enabled, seccomp fails to compile with errors like:

  error: enumerator value for '__cgo_enum__0' is not an integer constant

This is due to https://github.com/golang/go/issues/14669.